#pragma once

// Generated by data_analysis/scripts/build_p3_model.py from validated real runs.
// Do not hand-edit thresholds; regenerate this file after changing the rig.
#include "features.h"

namespace p3_model {

inline ClassifierConfig classifierConfig() {
    return ClassifierConfig{
        0.0227677846f,
        {0.0198115492f, 4.27310062f, 6.09323484e-05f, 176.523557f},
        {0.00146609074f, 0.770975822f, 1.0502295e-05f, 89.2782917f},
        {1.0f, 1.0f, 1.0f, 1.0f},
        1.47389821f,
        1.31447516f,
    };
}

inline const char* modelId() { return "d234ba342344"; }

}  // namespace p3_model
