"""Export reproducible model metadata and a P3-owned C++ header."""

import json
from pathlib import Path


def save_json(path, value):
    Path(path).write_text(json.dumps(value, indent=2, ensure_ascii=False,
                                     allow_nan=False) + "\n", encoding="utf-8")


def export_header(model, path):
    def number(value):
        text = format(float(value), ".9g")
        if "." not in text and "e" not in text.lower():
            text += ".0"
        return text + "f"

    def values(name):
        return "{" + ", ".join(number(value) for value in model[name]) + "}"

    config = model["feature_config"]
    source = model["source"]
    content = f'''// Generated by P3 from {source} data. Do not edit by hand.
// A simulated model is for software demonstration only.
#pragma once
#include "features.h"

namespace p3_fan_model {{
constexpr bool IS_MEASURED_DATA = {str(source == "measured").lower()};
constexpr int WINDOW_SIZE = {config["window_size"]};
constexpr float SAMPLE_RATE_HZ = {number(config["sample_rate_hz"])};

inline FeatureConfig featureConfig() {{
    return {{{number(config["band_low_hz"])}, {number(config["band_high_hz"])},
             {str(config["remove_mean"]).lower()}}};
}}

inline ClassifierConfig classifierConfig() {{
    return {{{number(model["rms_threshold"])}, {values("means")},
             {values("scales")}, {values("weights")},
             {number(model["score_threshold"])}}};
}}
}}  // namespace p3_fan_model
'''
    Path(path).write_text(content, encoding="utf-8")
