[platformio]
default_envs = esp32-s3-devkitc-1

[env]
platform = espressif32@6.10.0
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 115200
upload_flags = --no-stub
build_unflags = -DARDUINO_EVENT_RUNNING_CORE=1
build_flags =
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_EVENT_RUNNING_CORE=0
    -DP1_ALARM_PIN=5
    -DP1_ALARM_ACTIVE_HIGH=0
    -DP1_RGB_LED_RED_PIN=6
    -DP1_RGB_LED_GREEN_PIN=7
    -DP1_RGB_LED_BLUE_PIN=8
    -DP1_RGB_LED_COMMON_ANODE=1

[env:esp32-s3-devkitc-1]
build_src_filter =
    +<*>
    -<diagnostics/>
    -<sampling_stub.cpp>
lib_deps =
    bblanchon/ArduinoJson@6.21.5
    paulstoffregen/OneWire@2.3.8

[env:p2-sampling-diagnostic]
build_src_filter =
    +<sampling.cpp>
    +<sensors/>
    +<diagnostics/p2_sampling_diagnostic.cpp>
lib_deps =
    paulstoffregen/OneWire@2.3.8

[env:p2-temperature-diagnostic]
build_src_filter =
    +<sensors/temperature.cpp>
    +<diagnostics/p2_temperature_diagnostic.cpp>
lib_deps =
    paulstoffregen/OneWire@2.3.8

[env:p2-temperature-onewire-diagnostic]
build_src_filter =
    +<diagnostics/p2_temperature_onewire_diagnostic.cpp>
lib_deps =
    paulstoffregen/OneWire@2.3.8
